name: CI for Snake Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Versi Node.js yang lebih baru

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
